-- Database: uscis

-- DROP DATABASE IF EXISTS uscis;

CREATE DATABASE uscis
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C.UTF-8'
    LC_CTYPE = 'C.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO uscis;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO uscis;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO uscis;

ALTER DEFAULT PRIVILEGES
GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO uscis;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON TYPES TO PUBLIC;